# Generated by Django 5.2.17 on 2026-09-09 15:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_order__gte', 0), ('value__gte', 0)), name='coupon_nonnegative'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='coupon_dates'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENTAGE'), _negated=True), ('value__lte', 100), _connector='OR'), name='coupon_percentage'), models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('times_used__lte', models.F('usage_limit')), _connector='OR'), name='coupon_usage')],
            },
        ),
    ]
