# Generated by Django 5.2.17 on 2026-09-09 15:21

import core.storage
import core.uploads
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_name', models.CharField(max_length=160)),
                ('momo_code', models.CharField(max_length=30)),
                ('momo_phone_number', models.CharField(blank=True, max_length=30)),
                ('payment_instructions', models.TextField()),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_payment_settings')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money')], default='MTN_MOMO', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('instructions_snapshot', models.JSONField(default=dict)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('screenshot', models.ImageField(blank=True, storage=core.storage.private_storage, upload_to=core.uploads.image_path, validators=[core.uploads.validate_image])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_nonnegative')],
            },
        ),
    ]
