# Generated by Django 5.2.17 on 2026-09-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepaymentsettings',
            name='momo_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='storepaymentsettings',
            name='momo_phone_number',
            field=models.CharField(default='0784888458', max_length=30),
        ),
    ]
