# Generated by Django 5.2.17 on 2026-09-09 15:21

import core.uploads
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to=core.uploads.image_path, validators=[core.uploads.validate_image])),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_store'), models.CheckConstraint(condition=models.Q(('shipping_fee__gte', 0)), name='shipping_nonnegative')],
            },
        ),
    ]
